# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

concurrency:
  group: ${{ github.repository }}-concurrency-for-workflow
  cancel-in-progress: false

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.12'

    - name: Install
      run: echo go install

    - name: Build
      run: echo go build

    - name: Test
      run: echo go test

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Code Scan
      run: echo code scan
      
    - name: Artifacts Scan
      run: echo artifacts scan

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Unit Test
      run: echo unit test

  deploy:
    runs-on: ubuntu-latest
    needs: [scan, test]
    steps:
    - name: Prepare
      run: echo prepare
      
    - name: Update
      run: echo update service
